spring:
  datasource:
      url: jdbc:mysql://192.168.1.86:3306/pang?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: customer
      password: 123456
      driver-class-name: com.alibaba.druid.proxy.DruidDriver
      platform: mysql
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    content-type: text/html
    cache: false
    check-template: true
  mail:
    host: smtp.qq.com
    username: 412046232@qq.com
    password: grxrvcvuzswibjjf
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.ssl.required: true
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ni.cai.pang.entity

logging:
  level:
    ni.cai.pang.mapper: TRACE


jwt:
  secret: pang