spring:
  mail:
    host: smtp.qq.com
    username: 412046232@qq.com
    password: grxrvcvuzswibjjf
    properties.mail.smtp.auth: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.ssl.required: true
  redis:
    host: localhost
    port: 6379
      max-active: 8
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: pang
logging:
  level:
    ni.cai.pang.repo: TRACE
jwt:
  secret: pang