spring:
  datasource:
      url: jdbc:mysql://192.168.1.86:3306/pang?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: customer
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    content-type: text/html
    cache: false
    check-template: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ni.cai.pang.entity

logging:
  level:
    ni.cai.pang.mapper: TRACE